name: Deploy React App

on:
  push:
    branches:
      - main  # Ganti dengan nama cabang yang Anda gunakan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Ganti dengan versi Node.js yang Anda gunakan

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Server
        env:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no hanifdev@hanifdev.my.id "cd /home/hanifdev/public_html/usaha-bersama-react && rm -rf dist && git pull && npm install && npm run build"
